- README.md
https://issues.folio.org/browse/UIEXPMGR-1
While it's helpful for reviewers to help identify …
> UIEXPMGR-1 update readme

- CHANGELOG.md
- src/ExportJob/ExportJob.js
- src/ExportJob/index.js
- src/ExportJobs/ExportJobs.js
- src/ExportJobs/ExportJobsList/ExportJobsList.js
- src/ExportJobs/ExportJobsList/index.js
- src/ExportJobs/apiQuery.js
- src/ExportJobs/index.js
- src/ExportManager.js
- src/hooks.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-2
Cover by unit tests with details implementation in all areas (filter, results, details)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> UIEXPMGR-2 Export manager layout

- CHANGELOG.md
- src/ExportJob/ExportJob.js
- src/ExportJob/ExportJob.test.js
- src/ExportJob/apiQuery.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-5
While it's helpful for reviewers to help identify …
> UIEXPMGR-5 Export manager - export job details

- CHANGELOG.md
- package.json
- src/ExportJob/ExportJob.test.js
- src/ExportJobs/ExportJobs.js
- src/ExportJobs/ExportJobs.test.js
- src/ExportJobs/ExportJobsFilters/ExportJobsFilters.js
- src/ExportJobs/ExportJobsFilters/ExportJobsFilters.test.js
- src/ExportJobs/ExportJobsFilters/index.js
- src/ExportJobs/ExportJobsList/ExportJobsList.test.js
- src/ExportJobs/constants.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-4
While it's helpful for reviewers to help identify …
> UIEXPMGR-4 Export manager - export jobs search and filters

- PERSONAL_DATA_DISCLOSURE.md
> UIEXPMGR-6 Add personal data disclosure form

- package.json
> UIPBEX-3 remove data-export-sprint interface

- src/ExportJob/ExportJob.js
- src/ExportJobs/ExportJobsList/ExportJobsList.js
- src/ExportJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-10 …
> UIEXPMGR-10 export manager sorting

- src/ExportJobs/ExportJobsList/ExportJobsList.js
- src/ExportJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-10 …
> UIEXPMGR-10 fix default sorting

- package.json
- src/common/components/ExportJobId/ExportJobId.js
https://issues.folio.org/browse/UIEXPMGR-10 …
> UIEXPMGR-10 permissions

- CHANGELOG.md
- package.json
- src/ExportJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-7
While it's helpful for reviewers to help identify …
> Release v1.0.0

- CHANGELOG.md
- src/ExportJobs/ExportJobsFilters/ExportJobsFilters.js
https://issues.folio.org/browse/UIEXPMGR-11 …
> UIEXPMGR-11 Unable to filter results by Source

- CHANGELOG.md
- Jenkinsfile
- package.json
https://issues.folio.org/browse/UIEXPMGR-13 …
> UIEXPMGR-13 Compile Translation Files into AST

- CHANGELOG.md
- package.json
- src/ExportEdiJobs/ExportEdiJobs.js
- src/ExportEdiJobs/ExportEdiJobs.test.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportEdiJobsFilters.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportEdiJobsFilters.test.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/ExportMethodFilter.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/ExportMethodFilter.test.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/index.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/useConfigs.js
- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/useConfigs.test.js
- src/ExportEdiJobs/ExportEdiJobsFilters/index.js
- src/ExportEdiJobs/ExportEdiJobsList/ExportEdiJobsList.js
- src/ExportEdiJobs/ExportEdiJobsList/ExportEdiJobsList.test.js
- src/ExportEdiJobs/ExportEdiJobsList/index.js
- src/ExportEdiJobs/apiQuery.js
- src/ExportEdiJobs/apiQuery.test.js
- src/ExportEdiJobs/index.js
- src/ExportJob/ExportJob.js
- src/ExportJobs/ExportJobs.test.js
- src/ExportManager.js
- src/common/components/Navigation/Navigation.js
- src/common/components/Navigation/Navigation.test.js
- src/common/components/Navigation/constants.js
- src/common/components/Navigation/index.js
- src/common/components/index.js
- src/common/constants.js
- src/hooks.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-26 …
> UIEXPMGR-26 Search and filter organization exports

- src/ExportEdiJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-26 …
> UIEXPMGR-26 update filter query config

- src/ExportEdiJobs/ExportEdiJobsFilters/ExportMethodFilter/ExportMethodFilter.js
> UIEXPMGR-26 Fix export method filter options

- CHANGELOG.md
- package.json
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.js
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.test.js
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.js
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.test.js
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/index.js
- src/ExportEdiJobs/ExportEdiJobs.js
- src/ExportEdiJobs/apiQuery.js
- src/common/hooks/index.js
- src/common/hooks/useExportJobScheduler/index.js
- src/common/hooks/useExportJobScheduler/useExportJobScheduler.js
- src/common/hooks/useExportJobScheduler/useExportJobScheduler.test.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-27 …
> UIEXPMGR-27 Third pane view - Rerun action

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobs.js
- src/ExportJobs/ExportJobs.js
https://issues.folio.org/browse/UIEXPMGR-31 …
> UIEXPMGR-31 Select filter should announce the number of Results in the Results List pane header

- CHANGELOG.md
- src/ExportEdiJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-36 …
> UIEXPMGR-36 Search and filter organization export logs NOT working

- CHANGELOG.md
- package.json
> UIEXPMGR-37 release v2.1.1

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIEXPMGR-39 …
> UIEXPMGR-39 update perms

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UIEXPMGR-33
https://issues.folio.org/browse/UIEXPMGR-41 …
> UIEXPMGR-33  Remove react-hot-loader from package.json

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.js
- src/ExportJob/ExportJob.js
- src/common/components/ExportJobId/ExportJobId.js
The link is enabled in Export Manager without required permissions
[UIEXPMGR-52](https://issues.folio.org/browse/UIEXPMGR-52)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and …
> UIEXPMGR-52: The link is enabled in Export Manager without required permissions

- CHANGELOG.md
- package.json
[UIEXPMGR-53](https://issues.folio.org/browse/UIEXPMGR-53) …
> Release v2.2.2

- CHANGELOG.md
- package.json
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.js
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.js
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.test.js
- src/common/constants.js
- src/common/hooks/index.js
- src/common/hooks/useExportConfig/index.js
- src/common/hooks/useExportConfig/useExportConfig.js
- src/common/hooks/useExportConfig/useExportConfig.test.js
- translations/ui-export-manager/en.json
https://issues.folio.org/browse/UIEXPMGR-60
- Add `Re-send` and `Download` buttons in Organizations job details action menu;
- Add hook to retrieve EDI job configs and adjust the display of `Re-run` menu item based on configs;
- Add unit tests.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> UIEXPMGR-60 Third pane view - Download and re-send actions

- package.json
https://issues.folio.org/browse/UIEXPMGR-60 …
> UIEXPMGR-60 add permission to fetch export config

- CHANGELOG.md
- src/ExportJobs/apiQuery.js
- src/ExportJobs/constants.js
- translations/ui-export-manager/en.json
- translations/ui-export-manager/en_GB.json
- translations/ui-export-manager/en_US.json
[UIEXPMGR-61](https://issues.folio.org/browse/UIEXPMGR-61) …
> UIEXPMGR-61:Filter bulk edit jobs in Export Manager

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.js
- src/ExportEdiJobs/ExportEdiJobsList/ExportEdiJobsList.js
- src/ExportJob/ExportJob.js
- src/ExportJobs/ExportJobsList/ExportJobsList.js
- src/common/components/ExportJobId/ExportJobId.js
- src/common/components/ExportJobId/ExportJobId.test.js
- src/common/hooks/index.js
- src/common/hooks/useSecureDownload/index.js
- src/common/hooks/useSecureDownload/useSecureDownload.js
- src/common/hooks/useSecureDownload/useSecureDownload.test.js
https://issues.folio.org/browse/UIEXPMGR-64
Do refactoring in Orchid to reuse hook
While …
> UIEXPMGR-64 Cannot re-run 1 day+ old holdings exports

- CHANGELOG.md
- package.json
- src/ExportJobs/ExportJobs.test.js
- src/ExportJobs/ExportJobsFilters/ExportJobsFilters.test.js
- src/ExportJobs/ExportJobsList/ExportJobsList.test.js
- src/ExportManager.test.js
> UIEXPMGR-71: Run Accessibility Checker and Color Contrast Analyzer tools

- CHANGELOG.md
- package.json
[UIEXPMGR-72](https://issues.folio.org/browse/UIEXPMGR-72) …
> UIEXPMGR-72: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- src/common/constants.js
Support for downloading `AUTH_HEADINGS_UPDATES` and `FAILED_LINKED_BIB_UPDATES` job types.
[UIEXPMGR-78](https://issues.folio.org/browse/UIEXPMGR-78)
https://user-images.githubusercontent.com/77053927/219739725-456e9671-0269-4b3f-b6d2-bc2fc755d20c.mp4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
> UIEXPMGR-78: Support for downloading AUTH_HEADINGS_UPDATES and FAILED_LINKED_BIB_UPDATES job types.

- src/ExportJob/ExportJob.js
- translations/ui-export-manager/en.json
Fix incorrect job type message in Export details
[UIEXPMGR-68](https://issues.folio.org/browse/UIEXPMGR-68)
> UIEXPMGR-68 Fix authority headings export type in export details

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.js
https://issues.folio.org/browse/UIEXPMGR-80
After download refactoring ([#116](https://github.com/folio-org/ui-export-manager/pull/116)), filename for a downloaded EDIFACT file was [missed](https://github.com/folio-org/ui-export-manager/pull/116/files#diff-b9ccabaefd8834213d870b9ed917065c69277432351aec5e22a1a1539f861d04R76)
Ideally all of the PRs involved …
> UIEXPMGR-80 Provide filename when download EDIFACT export job

- src/ExportJobs/ExportJobsList/ExportJobsList.js
Fix incorrect job type in exports list
[UIEXPMGR-68](https://issues.folio.org/browse/UIEXPMGR-68)
> UIEXPMGR-68 Fix authority heading updates type in jobs list

- CHANGELOG.md
- src/ExportJobs/constants.js
https://issues.folio.org/browse/UIEXPMGR-62 …
> UIEXPMGR-62 Add EDIFACT orders export to job type filter in Export manager

- CHANGELOG.md
- src/ExportEdiJobs/apiQuery.js
https://issues.folio.org/browse/UIEXPMGR-81 …
> UIEXPMGR-81 Sorting EDI export jobs by export method

- CHANGELOG.md
- src/common/components/ExportJobId/ExportJobId.js
> UIEXPMGR-83 A hyperlink on the "JobID" column is not clickable with Users In app permissions

- CHANGELOG.md
- package.json
> Release v2.4.3

- CHANGELOG.md
- translations/ui-export-manager/en.json
[UIEXPMGR-89](https://issues.folio.org/browse/UIEXPMGR-89) - fix grammatical error
- update translation with correct grammatical format
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UIEXPMGR-66 - Grammatical error in export job

- CHANGELOG.md
- src/common/components/ExportJobId/ExportJobId.js
[UIEXPMGR-90](https://issues.folio.org/browse/UIEXPMGR-90) …
> UIEXPMGR-90: Export Manager downloads extra file

- package.json
- src/ExportEdiJobs/ExportEdiJobDetails/ExportEdiJobDetails.js
- src/common/components/ExportJobId/ExportJobId.js
- translations/ui-export-manager/en.json
As part of this story, it was necessary to add a view only permissions for the export manager. All active elements, links, menu actions - have been removed.
https://issues.folio.org/browse/UIEXPMGR-74
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …
> UIEXPMGR-74 Need new permission(s) to view Export Manager app in UI

- .eslintrc
- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
- src/common/components/ExportJobId/ExportJobId.js
[UIEXPMGR-94](https://issues.folio.org/browse/UIEXPMGR-94) …
> UIEXPMGR-94: Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobs.js
- src/ExportEdiJobs/ExportEdiJobs.test.js
- src/ExportJobs/ExportJobs.js
- src/ExportJobs/ExportJobs.test.js
- translations/ui-export-manager/en.json
https://folio-org.atlassian.net/browse/UIEXPMGR-105
He are we added `TitleManager` for page title handle.
> UIEXPMGR-105: Update HTML Page Title on Export Manager Tabs Page

- CHANGELOG.md
- src/ExportEdiJobs/ExportEdiJobDetailsActionMenu/ExportEdiJobDetailsActionMenu.js
- src/common/components/ExportJobId/ExportJobId.js
- src/common/constants.js
- src/common/hooks/useSecureDownload/useSecureDownload.js
- src/common/hooks/useSecureDownload/useSecureDownload.test.js
https://folio-org.atlassian.net/browse/UIEXPMGR-106 …
> UIEXPMGR-106 Update logic related to download files

- src/common/components/ExportJobId/ExportJobId.js
- src/common/hooks/useSecureDownload/useSecureDownload.js
> UIEXPMGR-106 keep a way to download files to not migrated jobs

- src/common/components/ExportJobId/ExportJobId.js
- src/common/constants.js
- src/common/hooks/useSecureDownload/useSecureDownload.js
> UIEXPMGR-106 parametrize download endpoint only fro multifiles jobs

- CHANGELOG.md
- src/ExportJobs/constants.js
- src/common/components/ExportJobId/ExportJobId.js
https://folio-org.atlassian.net/browse/UIEXPMGR-109
Here we added new conditions for downloading bulk-edit files regarding set permissions
> UIEXPMGR-109: Permissions cleanup for  Instance records

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- translations/ui-export-manager/en.json
[UIEXPMGR-112](https://folio-org.atlassian.net/browse/UIEXPMGR-112): UX - Removal of hyphen in Resend
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UIEXPMGR-112: UX - Removal of hyphen in Resend

- package.json
- translations/ui-export-manager/en.json
> UIBULKED-547 clean up ui-export-manager-permissions

- src/ExportJobs/constants.js
> UIBULKED-545 Align permissions with bulk edit

- src/ExportJobs/apiQuery.js
- src/ExportJobs/apiQuery.test.js
> UIEXPMGR-113 fix query by type

- src/settings/JobsSettings/components/JobDeletionIntervals/JobDeletionIntervals.css
- src/settings/JobsSettings/components/JobDeletionIntervals/JobDeletionIntervals.js
https://folio-org.atlassian.net/browse/UIEXPMGR-129
Base PR - #235 
https://github.com/user-attachments/assets/258debbd-c131-41d5-bbc6-7b95f8d4139e
> UIEXPMGR-129 Add intervals validation
